apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ''
    workload.cce.io/swr-version: '[{"version":"Third Party Edition"}]'
  labels:
    appgroup: ''
    version: v1
  name: front-end
  namespace: default
spec:
  selector:
    matchLabels:
      app: front-end
      version: v1
  template:
    metadata:
      labels:
        app: front-end
        version: v1
    spec:
      containers:
        - name: front-end
          image: >-
            swr.tr-west-1.myhuaweicloud.com/caglar-k8s-images/new-web-site:${version}
          imagePullPolicy: IfNotPresent
          env:
            - name: PAAS_APP_NAME
              value: front-end
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: a8dd91fe2b794d1f9dc66bcc30aa1f4c
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 512Mi
      imagePullSecrets:
        - name: default-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      initContainers: []
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  progressDeadlineSeconds: 600


---
apiVersion: v1
kind: Service
metadata:
  name: front-end-caglar-cluster
  labels:
    app: front-end
    version: v1
  namespace: default
  #annotations:
    #kubernetes.io/elb.class: performance
    #kubernetes.io/elb.autocreate: >-
    #  {"type":"inner","available_zone":["tr-west-1a","tr-west-1b"],"elb_virsubnet_ids":["603dc864-fc24-46c3-82f9-b30034b99a0d"],"ipv6_vip_virsubnet_id":"603dc864-fc24-46c3-82f9-b30034b99a0d","l4_flavor_name":"L4_flavor.elb.pro.max","l7_flavor_name":"","vip_subnet_cidr_id":"4c93ed7f-1601-477a-a6fc-7f833fa79889"}
    #kubernetes.io/elb.enterpriseID: b47f843a-ded2-49a4-a662-53a7033e5861
    #kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
    #kubernetes.io/elb.health-check-flag: 'on'
    #kubernetes.io/elb.health-check-option: '{"protocol":"TCP","delay":"5","timeout":"10","max_retries":"3"}'
spec:
  selector:
    app: front-end
    version: v1
  externalTrafficPolicy: Cluster
  ports:
    - name: cce-service-0
      targetPort: 80
      nodePort: 0
      port: 80
      protocol: TCP
  type: LoadBalancer

